version = 5.8.0
archive_dir = /etc/letsencrypt/archive/gps.sinergychile.cl
cert = /etc/letsencrypt/live/gps.sinergychile.cl/cert.pem
privkey = /etc/letsencrypt/live/gps.sinergychile.cl/privkey.pem
chain = /etc/letsencrypt/live/gps.sinergychile.cl/chain.pem
fullchain = /etc/letsencrypt/live/gps.sinergychile.cl/fullchain.pem
[renewalparams]
account = 0252bdb6646542943d81d38ee0e85c7f
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
